/**
 * Plan Mode Extension
 *
 * Adds /plan, /endplan, /writeplan, and /summarize commands, plus an optional
 * auto-save hook that snapshots the conversation to disk after every turn.
 *
 * - /plan              switches to the configured plan model, disables blocked
 * tools, and appends planning instructions to the system prompt
 * so the model produces a numbered markdown implementation plan.
 * - /writeplan [file]  Saves the last assistant response to PLAN.md (or the
 * specified file). If the file already exists and is non-empty,
 * prompts for write / append / clear / delete.
 * - /summarize         Summarizes the conversation using the configured
 * summarizer model + `summarizerPrompt`, writing the result
 * to `summarizeDir/<date>-<id>.md`.
 * - /endplan           restores the previous model and thinking level.
 *
 * Auto-save: if `autoSaveDir` is set in the config, the extension writes a
 * dated, summarizer-titled markdown snapshot of the session to that directory
 * after every completed agent turn. The title comes from running the
 * summarizer over the first 3 user prompts.
 */

import type { Model } from "@earendil-works/pi-ai";
import { complete } from "@earendil-works/pi-ai/compat";
import type {
	ExtensionAPI,
	ExtensionContext,
} from "@earendil-works/pi-coding-agent";
import type {
	SessionEntry,
	SessionManager,
} from "@earendil-works/pi-coding-agent";
import {
	CONFIG_DIR_NAME,
	getAgentDir,
	getPackageDir,
} from "@earendil-works/pi-coding-agent";
import {
	appendFileSync,
	existsSync,
	mkdirSync,
	readFileSync,
	statSync,
	unlinkSync,
	writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";

interface PlanModeConfig {
	provider?: string;
	model?: string;
	thinkingLevel?: "off" | "minimal" | "low" | "medium" | "high" | "xhigh";
	planFile?: string; // Kept in config schema as requested
	instructions?: string;
	blockList?: string[];
	/** Provider id for the summarizer. Defaults to the current model. */
	summarizerProvider?: string;
	/** Model id for the summarizer. Defaults to the current model. */
	summarizerModel?: string;
	/** Prompt sent to the summarizer for the /summarize command. */
	summarizerPrompt?: string;
	/** Directory where /summarize writes its output. */
	summarizeDir?: string;
	/**
	 * If set, the extension writes a dated markdown snapshot of the session
	 * to this directory after every completed agent turn. Filename is
	 * `<date>-<safe-summary>.md` where the safe summary is generated by the
	 * summarizer from the first 3 user prompts.
	 */
	autoSaveDir?: string;
}

interface PlanState {
	providerId: string | undefined;
	modelId: string | undefined;
	thinkingLevel: "off" | "minimal" | "low" | "medium" | "high" | "xhigh";
}

const DEFAULT_CONFIG: PlanModeConfig = {
	provider: "opencode-go",
	model: "qwen3.7-max",
	thinkingLevel: "high",
	planFile: "PLAN.md",
	blockList: ["edit", "write"],
	instructions:
		"You are a meticulous implementation planner.\n" +
		"If needed, use tools and subagents purely to explore the codebase and gather information first.\n" +
		"Once you have gathered all necessary context, output a numbered step-by-step implementation plan to solve the request containing:\n" +
		"1. The specific file(s) to create or modify at each step.\n" +
		"2. What change to make and why.\n" +
		"3. Any prerequisite steps (migrations, installs, config changes).\n" +
		'4. A short "Definition of Done" for the whole task.\n\n' +
		"Keep each step atomic and independently verifiable.\n" +
		"If applicable, identify all the places that need changes or might break due to these changes and revise your plan based on your findings.\n" +
		"When finished, output the final plan as a markdown file without fluff.",
};

const DEFAULT_INSTRUCTIONS = DEFAULT_CONFIG.instructions!;

const DEFAULT_SUMMARIZER_PROMPT =
	"Summarize this conversation in clear, structured markdown. Include: " +
	"(1) overall achievements, decisions and tradeoffs made, and (2) interesting questions/answers/discoveries." +
	"Prefer to be concise but include details when details are the point.";

export default function planModeExtension(pi: ExtensionAPI) {
	let config: PlanModeConfig = {};
	let planModeActive = false;
	let savedState: PlanState | undefined;

	/** Expand a leading "~" or "~/" to the user's home directory. */
	function expandHome(p: string): string {
		if (p === "~") return homedir();
		if (p.startsWith("~/") || p.startsWith("~\\"))
			return homedir() + p.slice(1);
		return p;
	}

	function loadConfig(ctx: ExtensionContext): PlanModeConfig {
		const globalPath = resolve(getAgentDir(), "plan-mode.json");
		const projectPath = resolve(ctx.cwd, CONFIG_DIR_NAME, "plan-mode.json");

		if (!existsSync(globalPath) && !existsSync(projectPath)) {
			try {
				mkdirSync(getAgentDir(), { recursive: true });
				writeFileSync(
					globalPath,
					JSON.stringify(DEFAULT_CONFIG, null, 2) + "\n",
					"utf8",
				);
				console.error(`plan-mode: wrote default config to ${globalPath}`);
			} catch (err) {
				console.error(
					`plan-mode: failed to write default config to ${globalPath}: ${err}`,
				);
			}
		}

		const merged: PlanModeConfig = { ...DEFAULT_CONFIG };

		for (const path of [globalPath, projectPath]) {
			if (!existsSync(path)) continue;
			try {
				const parsed = JSON.parse(readFileSync(path, "utf8"));
				if (parsed.provider) merged.provider = parsed.provider;
				if (parsed.model) merged.model = parsed.model;
				if (parsed.thinkingLevel) merged.thinkingLevel = parsed.thinkingLevel;
				if (parsed.planFile) merged.planFile = parsed.planFile;
				if (parsed.instructions) merged.instructions = parsed.instructions;
				if (parsed.blockList) merged.blockList = parsed.blockList;
				if (parsed.summarizerProvider) {
					merged.summarizerProvider = parsed.summarizerProvider;
				}
				if (parsed.summarizerModel) {
					merged.summarizerModel = parsed.summarizerModel;
				}
				if (parsed.summarizerPrompt) {
					merged.summarizerPrompt = parsed.summarizerPrompt;
				}
				if (parsed.summarizeDir) merged.summarizeDir = parsed.summarizeDir;
				if (parsed.autoSaveDir) merged.autoSaveDir = parsed.autoSaveDir;
			} catch (err) {
				console.error(`plan-mode: failed to parse ${path}: ${err}`);
				ctx.ui.notify(
					`plan-mode: Failed to parse configuration at ${path}.`,
					"warning",
				);
			}
		}
		// Expand leading "~" / "~/" in directory fields so users can write
		// "~/.pi/saved/html" in their config and have it resolve correctly
		// across platforms. `path.resolve` does not do this for us.
		if (merged.summarizeDir)
			merged.summarizeDir = expandHome(merged.summarizeDir);
		if (merged.autoSaveDir) merged.autoSaveDir = expandHome(merged.autoSaveDir);
		return merged;
	}

	async function enablePlanMode(ctx: ExtensionContext): Promise<void> {
		if (planModeActive) {
			ctx.ui.notify("Already in plan mode", "info");
			return;
		}

		if (!savedState) {
			savedState = {
				providerId: ctx.model?.provider.id,
				modelId: ctx.model?.id,
				thinkingLevel: pi.getThinkingLevel(),
			};
		}

		if (config.provider && config.model) {
			const model = ctx.modelRegistry.find(config.provider, config.model);
			if (!model) {
				ctx.ui.notify(
					`plan-mode: model ${config.provider}/${config.model} not found in registry. Aborting.`,
					"error",
				);
				return;
			}

			const ok = await pi.setModel(model);
			if (!ok) {
				ctx.ui.notify(
					`plan-mode: no API key for ${config.provider}/${config.model}. Aborting.`,
					"error",
				);
				return;
			}
		} else {
			ctx.ui.notify(
				"plan-mode: no model configured, keeping current model",
				"warning",
			);
		}

		if (config.thinkingLevel) {
			pi.setThinkingLevel(config.thinkingLevel);
		}

		planModeActive = true;
		ctx.ui.setStatus("plan-mode", ctx.ui.theme.fg("accent", "plan mode"));

		pi.appendEntry("plan-mode-state", { active: true, savedState });

		const currentBlockList = config.blockList ?? [];
		const blockMsg =
			currentBlockList.length > 0
				? ` [Blocked: ${currentBlockList.join(", ")}]`
				: " [All tools allowed]";
		ctx.ui.notify(`Plan mode enabled${blockMsg}`, "info");
	}

	async function disablePlanMode(ctx: ExtensionContext): Promise<void> {
		if (!planModeActive) {
			ctx.ui.notify("Not in plan mode", "info");
			return;
		}

		if (savedState) {
			if (savedState.providerId && savedState.modelId) {
				const model = ctx.modelRegistry.find(
					savedState.providerId,
					savedState.modelId,
				);
				if (model) {
					await pi.setModel(model);
				}
			}
			pi.setThinkingLevel(savedState.thinkingLevel);
		}

		planModeActive = false;
		savedState = undefined;
		ctx.ui.setStatus("plan-mode", undefined);

		pi.appendEntry("plan-mode-state", { active: false, savedState: undefined });

		ctx.ui.notify("Plan mode disabled", "info");
	}

	function getLastAssistantText(ctx: ExtensionContext): string | undefined {
		// Replicates AgentSession.getLastAssistantText(): a session entry wraps
		// the AgentMessage in { type: "message", message: AgentMessage, ... }.
		// Walk entries newest-first and concatenate the text content blocks.
		const lastAssistant = ctx.sessionManager.getEntries().findLast((e) => {
			if (e.type !== "message") return false;
			const msg = (
				e as {
					message?: { role?: string; stopReason?: string; content?: unknown[] };
				}
			).message;
			if (msg?.role !== "assistant") return false;
			// Skip aborted empty messages (matches AgentSession behaviour).
			if (msg.stopReason === "aborted" && (msg.content?.length ?? 0) === 0) {
				return false;
			}
			return true;
		});
		if (!lastAssistant) return undefined;
		const content = (
			lastAssistant as {
				message: { content: { type: string; text?: string }[] };
			}
		).message.content;
		let text = "";
		for (const block of content) {
			if (block.type === "text" && typeof block.text === "string") {
				text += block.text;
			}
		}
		text = text.trim();
		return text || undefined;
	}

	async function handleWritePlan(args: unknown, ctx: ExtensionContext) {
		const file =
			typeof args === "string" && args.trim() ? args.trim() : "PLAN.md";
		const filePath = resolve(ctx.cwd, file);

		const text = getLastAssistantText(ctx);
		if (!text) {
			ctx.ui.notify("No assistant message found to save.", "error");
			return;
		}

		if (existsSync(filePath) && statSync(filePath).size > 0) {
			if (!ctx.hasUI) {
				ctx.ui.notify(
					`${file} already exists. Run interactively to choose overwrite/append/clear/delete.`,
					"warning",
				);
				return;
			}
			const choice = await ctx.ui.select(
				`${file} already exists. What do you want to do?`,
				["write", "append", "clear", "delete"],
			);
			if (!choice) return; // user cancelled

			try {
				switch (choice) {
					case "write":
						writeFileSync(filePath, text, "utf8");
						ctx.ui.notify(`Wrote plan to ${file}`, "success");
						break;
					case "append":
						appendFileSync(
							filePath,
							(existsSync(filePath) ? "\n\n" : "") + text,
							"utf8",
						);
						ctx.ui.notify(`Appended plan to ${file}`, "success");
						break;
					case "clear":
						writeFileSync(filePath, "", "utf8");
						ctx.ui.notify(`Cleared ${file}`, "success");
						break;
					case "delete":
						unlinkSync(filePath);
						ctx.ui.notify(`Deleted ${file}`, "success");
						break;
				}
			} catch (err) {
				ctx.ui.notify(`Failed to ${choice} ${file}: ${err}`, "error");
			}
			return;
		}

		try {
			writeFileSync(filePath, text, "utf8");
			ctx.ui.notify(`Wrote plan to ${file}`, "success");
		} catch (err) {
			ctx.ui.notify(`Failed to write ${file}: ${err}`, "error");
		}
	}

	// =========================================================================
	// Summarization helpers (/summarize + autoSaveDir)
	// =========================================================================

	/** Returns the first `n` user messages from the current branch. */
	function getFirstUserPrompts(entries: SessionEntry[], n: number): string[] {
		const out: string[] = [];
		for (const e of entries) {
			if (e.type !== "message") continue;
			const msg = (e as { message?: { role?: string; content?: unknown } })
				.message;
			if (msg?.role !== "user") continue;
			const text = extractText(msg.content);
			if (text) out.push(text);
			if (out.length >= n) break;
		}
		return out;
	}

	/** Concatenate text from a message content field (string or content[]). */
	function extractText(content: unknown): string {
		if (typeof content === "string") return content;
		if (!Array.isArray(content)) return "";
		let s = "";
		for (const block of content) {
			if (
				block &&
				typeof block === "object" &&
				(block as { type?: string }).type === "text" &&
				typeof (block as { text?: unknown }).text === "string"
			) {
				s += (block as { text: string }).text;
			}
		}
		return s;
	}

	/** Build a plain-text version of the conversation for the summarizer. */
	function buildConversationText(entries: SessionEntry[]): string {
		const sections: string[] = [];
		for (const e of entries) {
			if (e.type !== "message") continue;
			const msg = (
				e as {
					message?: { role?: string; content?: unknown; stopReason?: string };
				}
			).message;
			if (!msg?.role) continue;
			if (msg.role !== "user" && msg.role !== "assistant") continue;
			if (msg.role === "assistant" && msg.stopReason === "aborted") continue;
			const text = extractText(msg.content).trim();
			if (text) {
				sections.push(`${msg.role === "user" ? "User" : "Assistant"}: ${text}`);
			}
		}
		return sections.join("\n\n");
	}

	/** Make a string safe to use as part of a filename. */
	function sanitizeFilename(s: string): string {
		const cleaned = s
			.toLowerCase()
			.replace(/[^a-z0-9]+/g, "-")
			.replace(/^-+|-+$/g, "")
			.slice(0, 60);
		return cleaned || "untitled";
	}

	/** YYYY-MM-DD in local time. */
	function dateStamp(d = new Date()): string {
		const yyyy = d.getFullYear();
		const mm = String(d.getMonth() + 1).padStart(2, "0");
		const dd = String(d.getDate()).padStart(2, "0");
		return `${yyyy}-${mm}-${dd}`;
	}

	/** Resolve the model to use for summarization, falling back to ctx.model. */
	function resolveSummarizerModel(ctx: ExtensionContext): {
		model: Model<any> | undefined;
		provider?: string;
		id?: string;
	} {
		const cfgProvider = config.summarizerProvider;
		const cfgModel = config.summarizerModel;
		if (cfgProvider && cfgModel) {
			return {
				model: ctx.modelRegistry.find(cfgProvider, cfgModel),
				provider: cfgProvider,
				id: cfgModel,
			};
		}
		if (cfgModel) {
			// try to find by id across known providers
			for (const m of ctx.modelRegistry.getAll()) {
				if (m.id === cfgModel) {
					return { model: m, provider: m.provider, id: m.id };
				}
			}
		}
		if (ctx.model) {
			return {
				model: ctx.model,
				provider: ctx.model.provider,
				id: ctx.model.id,
			};
		}
		return { model: undefined };
	}

	/**
	 * Run a single user prompt against the summarizer model and return the
	 * response text. Returns undefined on auth/lookup failure or no model.
	 */
	async function callSummarizer(
		userPrompt: string,
		ctx: ExtensionContext,
		systemPrompt?: string,
	): Promise<string | undefined> {
		const { model } = resolveSummarizerModel(ctx);
		if (!model) {
			ctx.ui.notify(
				"summarizer: no model available (no current model and none configured)",
				"error",
			);
			return undefined;
		}
		const auth = await ctx.modelRegistry.getApiKeyAndHeaders(model);
		if (!auth.ok) {
			ctx.ui.notify(`summarizer: ${auth.error}`, "error");
			return undefined;
		}
		if (!auth.apiKey) {
			ctx.ui.notify(
				`summarizer: no API key for ${model.provider}/${model.id}`,
				"error",
			);
			return undefined;
		}
		const messages = [
			{
				role: "user" as const,
				content: [{ type: "text" as const, text: userPrompt }],
				timestamp: Date.now(),
			},
		];
		try {
			const response = await complete(
				model,
				{
					...(systemPrompt ? { systemPrompt } : {}),
					messages,
				},
				{
					apiKey: auth.apiKey,
					headers: auth.headers,
					reasoningEffort: "low",
				},
			);
			return response.content
				.filter((c): c is { type: "text"; text: string } => c.type === "text")
				.map((c) => c.text)
				.join("\n")
				.trim();
		} catch (err) {
			ctx.ui.notify(
				`summarizer: call failed — ${err instanceof Error ? err.message : String(err)}`,
				"error",
			);
			return undefined;
		}
	}

	/** Short, hard-coded prompt for generating a filename slug from prompts. */
	const FILENAME_PROMPT = (prompts: string[]) =>
		`Generate a 2-5 word title that captures the main topic of this conversation. ` +
		`Reply with ONLY the title — no quotes, no punctuation, no preamble.\n\n` +
		prompts
			.map((p, i) => `<prompt-${i + 1}>\n${p}\n</prompt-${i + 1}>`)
			.join("\n\n");

	async function writeMarkdown(
		dir: string,
		file: string,
		body: string,
		ctx: ExtensionContext,
	) {
		try {
			if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
			const filePath = resolve(dir, file);
			writeFileSync(filePath, body, "utf8");
			ctx.ui.notify(`Wrote ${filePath}`, "success");
			return filePath;
		} catch (err) {
			ctx.ui.notify(`Failed to write ${file}: ${err}`, "error");
			return undefined;
		}
	}

	// =========================================================================
	// HTML export (reuses pi's internal exportSessionToHtml).
	//
	// pi's /export command is a TUI-only slash command and can't be invoked
	// programmatically from an extension. The underlying function lives at
	// <pkg>/dist/core/export-html/index.js, which is not in the package's
	// public exports map. We bypass that by computing the file:// URL from
	// getPackageDir() and importing it directly. This depends on the internal
	// path staying stable across pi releases, which has been the case so far.
	// =========================================================================
	type ExportHtmlFn = (
		sm: SessionManager,
		state?: unknown,
		options?: { outputPath?: string; themeName?: string } | string,
	) => Promise<string>;
	let exportHtmlCache: Promise<ExportHtmlFn> | undefined;
	function loadExportSessionToHtml(): Promise<ExportHtmlFn> {
		if (!exportHtmlCache) {
			const pkgDir = getPackageDir();
			const exportHtmlPath = resolve(
				pkgDir,
				"dist",
				"core",
				"export-html",
				"index.js",
			);
			const url = pathToFileURL(exportHtmlPath).href;
			exportHtmlCache = import(url).then(
				(mod) =>
					(mod as { exportSessionToHtml: ExportHtmlFn }).exportSessionToHtml,
			);
		}
		return exportHtmlCache;
	}

	async function writeSessionHtml(
		sm: SessionManager,
		outputPath: string,
		ctx: ExtensionContext,
	): Promise<string | undefined> {
		try {
			const exportSessionToHtml = await loadExportSessionToHtml();
			// exportSessionToHtml only reads getSessionFile/getEntries/getHeader/getLeafId,
			// all of which are part of ReadonlySessionManager, so the readonly view
			// is enough at runtime. The cast is just to satisfy the type signature.
			return await exportSessionToHtml(
				sm as unknown as SessionManager,
				undefined,
				{ outputPath },
			);
		} catch (err) {
			ctx.ui.notify(
				`plan-mode: HTML export failed — ${err instanceof Error ? err.message : String(err)}`,
				"error",
			);
			return undefined;
		}
	}

	async function handleSummarizeCommand(ctx: ExtensionContext) {
		const dir = config.summarizeDir;
		if (!dir) {
			ctx.ui.notify(
				"summarize: set `summarizeDir` in plan-mode.json to use /summarize",
				"error",
			);
			return;
		}
		const entries = ctx.sessionManager.getBranch() as SessionEntry[];
		const text = buildConversationText(entries);
		if (!text) {
			ctx.ui.notify("No conversation to summarize", "warning");
			return;
		}
		const prompt = config.summarizerPrompt ?? DEFAULT_SUMMARIZER_PROMPT;
		const wrapped = `${prompt}\n\n<conversation>\n${text}\n</conversation>`;
		if (ctx.hasUI) ctx.ui.notify("Summarizing conversation…", "info");
		const summary = await callSummarizer(wrapped, ctx);
		if (!summary) return;
		const id = sanitizeFilename(ctx.sessionManager.getSessionId().slice(0, 8));
		const file = `${dateStamp()}-${id}.md`;
		const body = `# Summary — ${dateStamp()}\n\n${summary}\n`;
		await writeMarkdown(dir, file, body, ctx);
	}

	async function handleAutoSave(ctx: ExtensionContext) {
		const dir = config.autoSaveDir;
		if (!dir) return;
		const entries = ctx.sessionManager.getBranch() as SessionEntry[];
		if (entries.length === 0) return;
		const firstPrompts = getFirstUserPrompts(entries, 3);
		if (firstPrompts.length === 0) return;
		const titleText = await callSummarizer(FILENAME_PROMPT(firstPrompts), ctx);
		// Fall back to a sanitized short session id if the summarizer returns
		// nothing (auth failure, model unavailable, empty response, etc.).
		const sessionId = ctx.sessionManager.getSessionId();
		const fallbackSlug = sanitizeFilename(sessionId.slice(0, 12));
		const slug = titleText ? sanitizeFilename(titleText) : fallbackSlug;
		if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
		const file = `${dateStamp()}-${slug}.html`;
		const outputPath = resolve(dir, file);
		const result = await writeSessionHtml(
			ctx.sessionManager as unknown as SessionManager,
			outputPath,
			ctx,
		);
		if (result) ctx.ui.notify(`Auto-saved ${result}`, "success");
	}

	pi.registerCommand("plan", {
		description: "Enter plan mode",
		handler: async (_args, ctx) => {
			await enablePlanMode(ctx);
		},
	});

	pi.registerCommand("endplan", {
		description: "Exit plan mode and restore previous model/tools",
		handler: async (_args, ctx) => {
			await disablePlanMode(ctx);
		},
	});

	pi.registerCommand("writeplan", {
		description:
			"Write the last assistant response to PLAN.md (or a specified file)",
		handler: async (args, ctx) => {
			await handleWritePlan(args, ctx);
		},
	});

	pi.registerCommand("summarize", {
		description:
			"Summarize the conversation and write to summarizeDir/<date>-<id>.md",
		handler: async (_args, ctx) => {
			await handleSummarizeCommand(ctx);
		},
	});

	pi.on("before_agent_start", (event, ctx) => {
		if (!planModeActive) return;

		return {
			systemPrompt: `${event.systemPrompt}\n\n${config.instructions ?? DEFAULT_INSTRUCTIONS}`,
		};
	});

	pi.on("tool_call", (event, ctx) => {
		if (!planModeActive) return;

		const currentBlockList = config.blockList ?? [];

		if (currentBlockList.includes(event.toolName)) {
			return {
				block: true,
				reason: `plan mode: ${event.toolName} is disallowed — work from the context provided and produce the plan as your text response`,
			};
		}
	});

	pi.on("session_shutdown", (_event, _ctx) => {
		planModeActive = false;
		savedState = undefined;
	});

	pi.on("agent_end", async (_event, ctx) => {
		// Fire-and-forget auto-save. Runs in the background so it doesn't
		// block the user; failures are reported via ctx.ui.notify inside
		// handleAutoSave / callSummarizer.
		if (!config.autoSaveDir) return;
		handleAutoSave(ctx).catch((err) => {
			ctx.ui.notify(
				`plan-mode: auto-save failed — ${err instanceof Error ? err.message : String(err)}`,
				"error",
			);
		});
	});

	pi.on("session_start", async (event, ctx) => {
		config = loadConfig(ctx);

		if (event.reason === "reload") return;

		const entries = ctx.sessionManager.getEntries();

		const lastStateEntry = entries.findLast(
			(e) =>
				e.type === "custom" &&
				(e as { customType?: string }).customType === "plan-mode-state",
		);

		if (lastStateEntry) {
			const entryData = (
				lastStateEntry as {
					data?: { active?: boolean; savedState?: PlanState };
				}
			).data;
			if (entryData?.active) {
				savedState = entryData.savedState;
				await enablePlanMode(ctx);
			}
		}
	});
}
